// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhiBEvzAlWGU7TcZ-7tZfzWx3L6bJOWc',
    appId: '1:429842870178:web:401515b25ab4d0c2fb8cfb',
    messagingSenderId: '429842870178',
    projectId: 'productive-imtihon',
    authDomain: 'productive-imtihon.firebaseapp.com',
    storageBucket: 'productive-imtihon.appspot.com',
    measurementId: 'G-0YBBM9N3CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA3O5CcsB52YEbU82qGfX-aFWdnp0BV8c',
    appId: '1:429842870178:android:2bf6b805ea4a63bbfb8cfb',
    messagingSenderId: '429842870178',
    projectId: 'productive-imtihon',
    storageBucket: 'productive-imtihon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf2867qCtjzNdermlZSpbUhtJfGAaS1ZU',
    appId: '1:429842870178:ios:c8ca9ea3da7f7ae4fb8cfb',
    messagingSenderId: '429842870178',
    projectId: 'productive-imtihon',
    storageBucket: 'productive-imtihon.appspot.com',
    iosBundleId: 'com.example.examProductive',
  );
}
